#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# creates files with data to play

import sys
import random

# The first byte of the line indicates the line type
LEDLINE = 1     # control byte (fade, blinking,...)+ 10*3 bytes (RGB) + '\n'
DELAYLINE = 2   # delay with time in seconds to wait for next line
TURNOFFLINE = 3 # turn off all LED strips
RINGLINE = 4    # control byte (fade, blinking,...)+ ring number + 3 bytes (RGB) + '\n'

# control byte indicates effects on line, information is coded in the bits
BLINKINGBIT = 1 # bit pattern 0000 0001
PULSINGBIT = 2  # bit pattern 0000 0010
FADINGBIT = 16  # bit pattern 0001 0000
ROLLINBIT = 32  # bit pattern 0010 0000
INOUTBIT = 48   # bit pattern 0011 0000
RANDOMBIT = 64  # bit pattern 0100 0000

# Number of Arduinos connecgted and I2C address offset as can't start address 1
NUMARDUINO = 10 # we have 10 Arduinos on I2C bus

# Some colors
RED = ['ff','00','00']
GREEN = ['00','ff','00']
BLUE = ['00','00','ff']
YELLOW = ['ff','ff','00']
CYAN = ['00','ff','ff']
PINK = ['ff','00','ff']
BLACK = ['00', '00', '00']
WHITE = ['ff', 'ff', 'ff']
ORANGE = ['ee', '33', '00']

def write_line(fd, controlByte, ring1, ring2, ring3, ring4, ring5, ring6, ring7, ring8, ring9, ring10):
  fd.write(chr(LEDLINE))
  fd.write(chr(controlByte))
  fd.write(chr(int(ring1[0],16)))
  fd.write(chr(int(ring1[1],16)))
  fd.write(chr(int(ring1[2],16)))
  fd.write(chr(int(ring2[0],16)))
  fd.write(chr(int(ring2[1],16)))
  fd.write(chr(int(ring2[2],16)))
  fd.write(chr(int(ring3[0],16)))
  fd.write(chr(int(ring3[1],16)))
  fd.write(chr(int(ring3[2],16)))
  fd.write(chr(int(ring4[0],16)))
  fd.write(chr(int(ring4[1],16)))
  fd.write(chr(int(ring4[2],16)))
  fd.write(chr(int(ring5[0],16)))
  fd.write(chr(int(ring5[1],16)))
  fd.write(chr(int(ring5[2],16)))
  fd.write(chr(int(ring6[0],16)))
  fd.write(chr(int(ring6[1],16)))
  fd.write(chr(int(ring6[2],16)))
  fd.write(chr(int(ring7[0],16)))
  fd.write(chr(int(ring7[1],16)))
  fd.write(chr(int(ring7[2],16)))
  fd.write(chr(int(ring8[0],16)))
  fd.write(chr(int(ring8[1],16)))
  fd.write(chr(int(ring8[2],16)))
  fd.write(chr(int(ring9[0],16)))
  fd.write(chr(int(ring9[1],16)))
  fd.write(chr(int(ring9[2],16)))
  fd.write(chr(int(ring10[0],16)))
  fd.write(chr(int(ring10[1],16)))
  fd.write(chr(int(ring10[2],16)))
  fd.write('\n')
  return;

def line_color(fd, ring_color):
  fd.write(chr(LEDLINE))
  fd.write('\x00')
  for i in range (1, 11):
      fd.write(chr(int(ring_color[0],16)))
      fd.write(chr(int(ring_color[1],16)))
      fd.write(chr(int(ring_color[2],16)))
  fd.write('\n')
  return;

def line_color_fade(fd, ring_color):
  fd.write(chr(LEDLINE))
  fd.write(chr(FADINGBIT))
  for i in range (1, 11):
      fd.write(chr(int(ring_color[0],16)))
      fd.write(chr(int(ring_color[1],16)))
      fd.write(chr(int(ring_color[2],16)))
  fd.write('\n')
  return;

def line_color_roll(fd, ring_color):
  fd.write(chr(LEDLINE))
  fd.write(chr(ROLLINBIT))
  for i in range (1, 11):
      fd.write(chr(int(ring_color[0],16)))
      fd.write(chr(int(ring_color[1],16)))
      fd.write(chr(int(ring_color[2],16)))
  fd.write('\n')
  return;

def line_color_inout(fd, ring_color):
  fd.write(chr(LEDLINE))
  fd.write(chr(INOUTBIT))
  for i in range (1, 11):
      fd.write(chr(int(ring_color[0],16)))
      fd.write(chr(int(ring_color[1],16)))
      fd.write(chr(int(ring_color[2],16)))
  fd.write('\n')
  return;

def line_color_random(fd, ring_color):
  fd.write(chr(LEDLINE))
  fd.write(chr(RANDOMBIT))
  for i in range (1, 11):
      fd.write(chr(int(ring_color[0],16)))
      fd.write(chr(int(ring_color[1],16)))
      fd.write(chr(int(ring_color[2],16)))
  fd.write('\n')
  return;

def line_delay(fd, time_to_wait):
  fd.write(chr(DELAYLINE))
  fd.write(chr(time_to_wait))
  fd.write('\n')
  return;

def line_turnoff(fd):
  fd.write(chr(TURNOFFLINE))
  fd.write('\n')
  return;

def makeRed(fd):
  write_line(fd, 0, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, RED, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, RED, RED, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, BLACK, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, BLACK, RED, RED, BLACK, BLACK, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, RED, BLACK, RED, RED, BLACK, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, BLACK, RED, RED, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, BLACK, BLACK, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, BLACK, RED, RED, BLACK, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, BLACK, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, RED, RED, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, RED, RED, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, RED, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  return;

def makeGreen(fd):
  write_line(fd, 0, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK, BLACK, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  return;

def makeBlue(fd):
  write_line(fd, 0, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  return;

def makeYellow(fd):
  write_line(fd, 0, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  return;

def makeCyan(fd):
  write_line(fd, 0, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, CYAN, CYAN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK, BLACK, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  return;

def makePink(fd):
  write_line(fd, 0, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, PINK, PINK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK, BLACK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, BLACK, BLACK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, PINK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, PINK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, PINK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  return;

def makeWhite(fd):
  write_line(fd, 0, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, BLACK, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  return;

def makeOrange(fd):
  write_line(fd, 0, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, ORANGE, ORANGE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK, BLACK, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  line_turnoff(fd)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, 0, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  return;

def makeRedEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, RED, RED, RED, BLACK, RED, RED, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, RED, RED, BLACK, RED, BLACK, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, BLACK, BLACK, RED, RED, RED, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, BLACK, BLACK, RED, BLACK, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, RED, RED, RED, RED, RED, BLACK, RED, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, RED, BLACK, BLACK, BLACK, RED, BLACK, RED, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, RED, RED, BLACK, BLACK, BLACK, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, RED, BLACK, BLACK, RED, RED, RED, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, RED, BLACK, RED, BLACK, RED, BLACK, RED, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, RED, RED, BLACK, RED, BLACK, RED, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, RED, BLACK, RED, BLACK, RED, BLACK, BLACK, RED, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, RED, RED, RED, BLACK, RED, RED, BLACK, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, RED, BLACK, RED, RED, RED, BLACK, RED, BLACK, RED, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, RED, RED, RED, BLACK, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, RED, BLACK, BLACK, BLACK, RED, BLACK, RED, BLACK, BLACK, RED)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, RED, RED, RED, BLACK, RED, BLACK, RED, RED, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED)
  return;

def makeGreenEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, GREEN, GREEN, BLACK, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, BLACK, BLACK, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, BLACK, BLACK, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, GREEN, BLACK, BLACK, BLACK, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, GREEN, BLACK, BLACK, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, GREEN, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, GREEN, BLACK, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, BLACK, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, GREEN, BLACK, GREEN, GREEN, GREEN, BLACK, GREEN, BLACK, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, GREEN, GREEN, GREEN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, GREEN, BLACK, BLACK, BLACK, GREEN, BLACK, GREEN, BLACK, BLACK, GREEN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, GREEN, GREEN, GREEN, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN)
  return;

def makeBlueEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLUE, BLUE, BLACK, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLACK, BLACK, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLACK, BLACK, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLUE, BLACK, BLACK, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLUE, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLUE, BLACK, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLACK, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLUE, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLACK, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLUE, BLACK, BLACK, BLUE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLACK, BLUE, BLUE, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE)
  return;

def makeYellowEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, YELLOW, YELLOW, BLACK, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, BLACK, BLACK, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, YELLOW, BLACK, BLACK, BLACK, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, YELLOW, BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, YELLOW, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, YELLOW, BLACK, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, BLACK, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, YELLOW, BLACK, BLACK, BLACK, YELLOW, BLACK, YELLOW, BLACK, BLACK, YELLOW)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, YELLOW, YELLOW, YELLOW, BLACK, YELLOW, BLACK, YELLOW, YELLOW, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW)
  return;

def makeCyanEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, CYAN, CYAN, BLACK, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, BLACK, BLACK, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, BLACK, BLACK, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, CYAN, BLACK, BLACK, BLACK, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, CYAN, CYAN, BLACK, BLACK, BLACK, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, CYAN, BLACK, BLACK, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, CYAN, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, CYAN, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, CYAN, BLACK, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, CYAN, BLACK, CYAN, CYAN, CYAN, BLACK, CYAN, BLACK, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, CYAN, BLACK, BLACK, BLACK, CYAN, BLACK, CYAN, BLACK, BLACK, CYAN)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, CYAN, CYAN, CYAN, BLACK, CYAN, BLACK, CYAN, CYAN, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN)
  return;

def makePinkEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, PINK, PINK, BLACK, PINK, BLACK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, BLACK, BLACK, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, BLACK, BLACK, PINK, BLACK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, PINK, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, PINK, BLACK, BLACK, BLACK, PINK, BLACK, PINK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, PINK, PINK, BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, PINK, BLACK, BLACK, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, PINK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, PINK, PINK, BLACK, PINK, BLACK, PINK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, PINK, BLACK, PINK, BLACK, PINK, BLACK, BLACK, PINK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, PINK, BLACK, PINK, PINK, PINK, BLACK, PINK, BLACK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, PINK, PINK, PINK, BLACK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, PINK, BLACK, BLACK, BLACK, PINK, BLACK, PINK, BLACK, BLACK, PINK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, PINK, PINK, PINK, BLACK, PINK, BLACK, PINK, PINK, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK)
  return;

def makeWhiteEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, WHITE, WHITE, BLACK, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, BLACK, BLACK, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, WHITE, BLACK, BLACK, BLACK, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, WHITE, BLACK, BLACK, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, WHITE, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, WHITE, BLACK, WHITE, WHITE, WHITE, BLACK, WHITE, BLACK, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, WHITE, BLACK, BLACK, BLACK, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, WHITE, WHITE, WHITE, BLACK, WHITE, BLACK, WHITE, WHITE, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE)
  return;

def makeOrangeEffect(fd):
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, ORANGE, ORANGE, BLACK, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, BLACK, BLACK, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, BLACK, BLACK, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, RANDOMBIT | BLINKINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 5)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, ORANGE, ORANGE, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, ORANGE, BLACK, BLACK, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, ROLLINBIT | BLINKINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 5)
  write_line(fd, INOUTBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, ORANGE, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, ORANGE, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, ORANGE, BLACK, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, BLACK, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK, ORANGE, BLACK, BLACK, ORANGE)
  line_delay(fd, 1)
  write_line(fd, INOUTBIT, BLACK, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, BLACK, ORANGE, ORANGE, BLACK)
  line_delay(fd, 1)
  write_line(fd, PULSINGBIT, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE)
  return;

if __name__ == "__main__":
  fd = open('./makeRed.dat', 'wb')
  makeRed(fd)
  fd.close()

  fd = open('./makeGreen.dat', 'wb')
  makeGreen(fd)
  fd.close()

  fd = open('./makeBlue.dat', 'wb')
  makeBlue(fd)
  fd.close()

  fd = open('./makeYellow.dat', 'wb')
  makeYellow(fd)
  fd.close()

  fd = open('./makeCyan.dat', 'wb')
  makeCyan(fd)
  fd.close()

  fd = open('./makePink.dat', 'wb')
  makePink(fd)
  fd.close()

  fd = open('./makeWhite.dat', 'wb')
  makeWhite(fd)
  fd.close()

  fd = open('./makeOrange.dat', 'wb')
  makeOrange(fd)
  fd.close()

  fd = open('./makeRedEffect.dat', 'wb')
  makeRedEffect(fd)
  fd.close()

  fd = open('./makeGreenEffect.dat', 'wb')
  makeGreenEffect(fd)
  fd.close()

  fd = open('./makeBlueEffect.dat', 'wb')
  makeBlueEffect(fd)
  fd.close()

  fd = open('./makeYellowEffect.dat', 'wb')
  makeYellowEffect(fd)
  fd.close()

  fd = open('./makeCyanEffect.dat', 'wb')
  makeCyanEffect(fd)
  fd.close()

  fd = open('./makePinkEffect.dat', 'wb')
  makePinkEffect(fd)
  fd.close()

  fd = open('./makeWhiteEffect.dat', 'wb')
  makeWhiteEffect(fd)
  fd.close()

  fd = open('./makeOrangeEffect.dat', 'wb')
  makeOrangeEffect(fd)
  fd.close()
